"""Observability package exposing OpenTelemetry tracer, Prometheus metrics, and Langfuse tracing."""

from app.observability.langfuse_client import LangfuseTracer
from app.observability.metrics import (
    CACHE_REQUESTS_TOTAL,
    CIRCUIT_BREAKER_TRIPPED_TOTAL,
    CRAG_REWRITE_ATTEMPTS_TOTAL,
    CRAG_WEB_FALLBACK_TOTAL,
    FEEDBACK_TOTAL,
    GATEWAY_CALLS_TOTAL,
    GATEWAY_FAILOVERS_TOTAL,
    GROUNDEDNESS_CHECKS_TOTAL,
    GROUNDEDNESS_SCORE_HISTOGRAM,
    LLM_LATENCY_SECONDS,
    NODE_LATENCY_SECONDS,
    REQUEST_LATENCY_SECONDS,
    get_metrics_exposition,
    record_cache_hit,
    record_cache_miss,
    record_circuit_breaker_trip,
    record_crag_rewrite,
    record_crag_web_fallback,
    record_feedback,
    record_gateway_call,
    record_gateway_failover,
    record_groundedness_check,
    record_node_latency,
)
from app.observability.tracer import (
    get_tracer,
    setup_tracer,
    trace_span,
    wrap_traced_node,
)

__all__ = [
    "CACHE_REQUESTS_TOTAL",
    "CIRCUIT_BREAKER_TRIPPED_TOTAL",
    "CRAG_REWRITE_ATTEMPTS_TOTAL",
    "CRAG_WEB_FALLBACK_TOTAL",
    "FEEDBACK_TOTAL",
    "GATEWAY_CALLS_TOTAL",
    "GATEWAY_FAILOVERS_TOTAL",
    "GROUNDEDNESS_CHECKS_TOTAL",
    "GROUNDEDNESS_SCORE_HISTOGRAM",
    "LLM_LATENCY_SECONDS",
    "NODE_LATENCY_SECONDS",
    "REQUEST_LATENCY_SECONDS",
    "LangfuseTracer",
    "get_metrics_exposition",
    "get_tracer",
    "record_cache_hit",
    "record_cache_miss",
    "record_circuit_breaker_trip",
    "record_crag_rewrite",
    "record_crag_web_fallback",
    "record_feedback",
    "record_gateway_call",
    "record_gateway_failover",
    "record_groundedness_check",
    "record_node_latency",
    "setup_tracer",
    "trace_span",
    "wrap_traced_node",
]
